"""Independent transcription of celda's DecontX C++ kernel.

This exists so the regression suite has a reference that was NOT produced by
decontx/. The golden fixtures are generated by this package, so comparing
against them can only detect drift -- never a shared error. This module is
transcribed directly from the upstream source and is deliberately naive: dense
numpy, no Numba, no shared code with decontx/.

Source: https://github.com/campbio/celda/blob/master/src/DecontX.cpp
  decontXInitialize  (lines 206-265)
  decontXEM          (lines 7-148)

Orientation note: R stores counts as genes x cells and phi/eta as
genes x clusters, so R's rowSums(phi) is a per-gene total across clusters and
R's colSums(phi) is a per-cluster total. This module uses the Python
convention (cells x genes, clusters x genes) and flips the axes accordingly.

The one component not transcribed line-for-line is MCMCprecision::fit_dirichlet,
which is a compiled R package. It is reimplemented here as Minka's fixed-point
Dirichlet MLE, the algorithm that function documents.
"""

import numpy as np
from scipy.special import digamma, polygamma
from scipy.stats import beta as beta_dist


def _inv_digamma(y, n_iter=5):
    """Invert digamma by Newton iteration (Minka 2000, appendix C)."""
    x = np.where(y >= -2.22, np.exp(y) + 0.5, -1.0 / (y - digamma(1.0)))
    for _ in range(n_iter):
        x = x - (digamma(x) - y) / polygamma(1, x)
    return x


def fit_dirichlet(x, max_iter=1000, tol=1e-10):
    """Minka's fixed-point MLE for Dirichlet alpha. Mirrors fit_dirichlet()."""
    x = np.clip(np.asarray(x, dtype=np.float64), 1e-12, None)
    log_p = np.log(x).mean(axis=0)

    # Moment-matching initialization.
    m = x.mean(axis=0)
    v = x.var(axis=0).mean()
    precision = max((m[0] * (1.0 - m[0]) / v) - 1.0, 1e-6) if v > 0 else 1.0
    alpha = m * precision

    for _ in range(max_iter):
        new_alpha = _inv_digamma(digamma(alpha.sum()) + log_p)
        if np.max(np.abs(new_alpha - alpha)) < tol:
            alpha = new_alpha
            break
        alpha = new_alpha
    return alpha


def decontx_initialize(counts, theta, z, n_clusters, pseudocount=1e-20):
    """Transcription of decontXInitialize (DecontX.cpp:206-265).

    Note `std::fill(new_phi, pseudocount)` seeds EVERY entry before
    accumulation, so the per-gene rowsum carries K * pseudocount.
    """
    n_cells, n_genes = counts.shape

    phi = np.full((n_clusters, n_genes), pseudocount)
    for j in range(n_cells):
        phi[z[j] - 1] += counts[j] * theta[j]

    gene_totals = phi.sum(axis=0)  # R: rowSums(new_phi)
    eta = gene_totals[None, :] - phi

    phi = phi / phi.sum(axis=1, keepdims=True)  # R: colSums normalization
    eta = eta / eta.sum(axis=1, keepdims=True)
    return phi, eta


def decontx_em(counts, counts_colsums, theta, eta, phi, z, delta, estimate_delta):
    """Transcription of decontXEM (DecontX.cpp:7-148).

    R adds pseudocount to theta as well as to phi/eta:
        pnative   = (phi + pc) * (theta + pc)
        pcontamin = (eta + pc) * (1 - theta + pc)
    """
    pc = 1e-20
    n_cells, n_genes = counts.shape

    new_phi = np.zeros_like(phi)
    native_total = np.zeros(n_cells)

    for j in range(n_cells):
        k = z[j] - 1
        pnative = (phi[k] + pc) * (theta[j] + pc)
        pcontamin = (eta[k] + pc) * (1.0 - theta[j] + pc)
        normp = pnative / (pcontamin + pnative)
        px = normp * counts[j]
        new_phi[k] += px
        native_total[j] = px.sum()

    gene_totals = new_phi.sum(axis=0)
    new_eta = gene_totals[None, :] - new_phi

    new_phi = new_phi / new_phi.sum(axis=1, keepdims=True)
    new_eta = new_eta / new_eta.sum(axis=1, keepdims=True)

    contamination_prop = (counts_colsums - native_total) / counts_colsums
    native_prop = 1.0 - contamination_prop

    new_delta = np.asarray(delta, dtype=np.float64)
    if estimate_delta:
        new_delta = fit_dirichlet(np.column_stack([native_prop, contamination_prop]))

    new_theta = (native_total + new_delta[0]) / (counts_colsums + new_delta.sum())

    return new_phi, new_eta, new_theta, new_delta, contamination_prop


def run_reference(
    X,
    z,
    delta=(10.0, 10.0),
    estimate_delta=True,
    max_iter=200,
    convergence=0.001,
    seed=12345,
):
    """Run the reference EM. Returns contamination, theta, phi, eta, delta.

    The initial theta is drawn the same way decontx does, so a comparison
    against this reference measures the algorithm rather than RNG divergence.
    """
    counts = np.asarray(X.todense() if hasattr(X, "todense") else X, dtype=np.float64)
    z = np.asarray(z, dtype=np.int64)

    unique = np.unique(z)
    z = np.searchsorted(unique, z) + 1
    n_clusters = len(unique)

    counts_colsums = counts.sum(axis=1)
    delta = np.asarray(delta, dtype=np.float64)

    theta = beta_dist.rvs(delta[0], delta[1], size=counts.shape[0], random_state=seed)
    phi, eta = decontx_initialize(counts, theta, z, n_clusters)

    n_iter = 0
    for iteration in range(max_iter):
        n_iter = iteration + 1
        theta_old = theta.copy()
        phi, eta, theta, delta, contamination = decontx_em(
            counts, counts_colsums, theta, eta, phi, z, delta, estimate_delta
        )
        if np.max(np.abs(theta - theta_old)) < convergence:
            break

    # R returns the contamination computed at the START of the final iteration,
    # from the pre-update theta -- so its reported contamination corresponds to a
    # different E-step than its reported counts. decontx instead runs one more
    # E-step with the converged parameters, which keeps contamination consistent
    # with the counts it returns. Advance the reference by that one step so the
    # two are directly comparable.
    pc = 1e-20
    native_final = np.zeros(counts.shape[0])
    for j in range(counts.shape[0]):
        k = z[j] - 1
        pnative = (phi[k] + pc) * (theta[j] + pc)
        pcontamin = (eta[k] + pc) * (1.0 - theta[j] + pc)
        native_final[j] = (counts[j] * pnative / (pnative + pcontamin)).sum()
    contamination_final = (counts_colsums - native_final) / counts_colsums

    return {
        "contamination": contamination,
        "contamination_final": contamination_final,
        "theta": theta,
        "phi": phi,
        "eta": eta,
        "delta": delta,
        "n_iter": n_iter,
    }
