"""Regression tests for decontx numerical accuracy.

The golden reference was generated by tests/generate_golden.py
on a fixed synthetic dataset. All tests compare against it.
"""

import os

import anndata as ad
import numpy as np
import pandas as pd

import decontx
from tests.generate_golden import make_dataset

GOLDEN_DIR = os.path.join(os.path.dirname(__file__), "golden")


def _load_golden():
    return {
        "theta": np.load(os.path.join(GOLDEN_DIR, "theta.npy")),
        "phi": np.load(os.path.join(GOLDEN_DIR, "phi.npy")),
        "eta": np.load(os.path.join(GOLDEN_DIR, "eta.npy")),
        "contamination": np.load(os.path.join(GOLDEN_DIR, "contamination.npy")),
        "decontX_counts": np.load(os.path.join(GOLDEN_DIR, "decontx_counts.npy")),
        "z": np.load(os.path.join(GOLDEN_DIR, "z.npy")),
        "delta": np.load(os.path.join(GOLDEN_DIR, "delta.npy")),
    }


def _run_current():
    """Run the current decontx implementation on the golden dataset."""
    adata, z = make_dataset()
    result = decontx.decontx(
        adata, cluster_key="leiden", copy=True, verbose=False, seed=12345, max_iter=200
    )
    return result


def _run_current_model_internals():
    """Run the model directly to get theta, phi, and eta."""
    adata, z = make_dataset()
    from decontx.model import DecontXModel

    X = adata.X
    z = np.ascontiguousarray(z, dtype=np.int32)
    model = DecontXModel(max_iter=200, convergence=0.001, seed=12345, verbose=False)
    return model.fit_transform(X, z)


def test_decontx_basic_runs():
    """Verify that decontx runs and produces the expected output keys."""
    np.random.seed(42)
    n_cells, n_genes = 100, 50
    X = np.random.poisson(5, size=(n_cells, n_genes))
    adata = ad.AnnData(X)
    adata.obs["leiden"] = pd.Categorical(np.repeat([1, 2, 3, 4], 25))
    result = decontx.decontx(adata, cluster_key="leiden", copy=True, verbose=False)
    assert "decontX_counts" in result.layers
    assert "decontX_contamination" in result.obs
    assert result.layers["decontX_counts"].shape == X.shape
    assert len(result.obs["decontX_contamination"]) == n_cells


def test_regression_contamination_bit_identical():
    """Contamination must match the golden reference to 1e-8."""
    golden = _load_golden()
    result = _run_current()
    contam = result.obs["decontX_contamination"].values
    assert contam.shape == golden["contamination"].shape
    max_abs_diff = np.max(np.abs(contam - golden["contamination"]))
    assert max_abs_diff < 1e-8, (
        f"Contamination differs from golden by max {max_abs_diff:.2e} "
        f"(expected < 1e-8)."
    )


def test_regression_theta_bit_identical():
    """Theta must match the golden reference to 1e-8."""
    golden = _load_golden()
    res = _run_current_model_internals()
    max_abs_diff = np.max(np.abs(res["theta"] - golden["theta"]))
    assert max_abs_diff < 1e-8, (
        f"theta differs from golden by max {max_abs_diff:.2e} (expected < 1e-8)."
    )


def test_regression_phi_eta_bit_identical():
    """Phi and eta must match the golden reference to 1e-8."""
    golden = _load_golden()
    res = _run_current_model_internals()
    phi_diff = np.max(np.abs(res["phi"] - golden["phi"]))
    eta_diff = np.max(np.abs(res["eta"] - golden["eta"]))
    assert phi_diff < 1e-8, f"phi differs by {phi_diff:.2e}"
    assert eta_diff < 1e-8, f"eta differs by {eta_diff:.2e}"


def test_regression_decontX_counts_bit_identical():
    """Decontaminated counts must match the golden reference exactly."""
    golden = _load_golden()
    result = _run_current()
    counts = result.layers["decontX_counts"]
    from scipy.sparse import issparse as _issparse

    if _issparse(counts):
        counts = counts.toarray()
    counts = np.asarray(counts)
    assert np.array_equal(counts, golden["decontX_counts"]), (
        "decontX_counts differ from golden."
    )


def test_regression_correlation_gate():
    """Contamination correlation with golden must exceed 0.999."""
    golden = _load_golden()
    result = _run_current()
    contam = result.obs["decontX_contamination"].values
    corr = np.corrcoef(contam, golden["contamination"])[0, 1]
    assert corr > 0.999, f"Correlation with golden = {corr:.6f} (expected > 0.999)."
